#server.port=8085
#server.contextPath=/currencyservice

logging:
  file: /var/log/rodrigovelaz/currency-exchange-service/currency-exchange-service.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/currency_exchange?useSSL=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jackson:
    serialization.write-dates-as-timestamps: false
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
