#server.port=8085
#server.contextPath=/currencyservice
#spring.jackson.serialization.write-dates-as-timestamps=false
#logging.file=/var/log/redmond/currencyservice/currencyservice
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/currency-exchange-service?useSSL=false
    username: currency-exchange-service
    password: currency-exchange-service
    testWhileIdle: true
    validationQuery: SELECT 1
  jackson:
    serialization.write-dates-as-timestamps=false
  jpa:
    show-sql: true
    properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
