logging:
  file: /var/log/rodrigovelaz/kafka-service/kafka-service.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

server:
  port: 8084

spring:
  jackson:
    serialization.write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${spring.application.name}
      max-poll-records: 10
    properties:
      max.poll.interval.ms: 300000

kafka:
  topics: test
  
  rest-servers:
    test: http://url:port/end
