logging:
  file: /var/log/rodrigovelaz/list-service/list-service.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

management:
  security:
    enabled: false
  #context-path: /management
  #port=9080

#server:
  #port: 8089
  #contextPath: /listservice

spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: create-drop
    hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  datasource:
    url: jdbc:mysql://localhost:3306/list?useSSL=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jackson.serialization.write-dates-as-timestamps: false
