logging:
  file: /var/log/rodrigovelaz/paypal-service/paypal-service.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

management:
  security:
    enabled: false
  #context-path: /management
  #port=9080

#server:
  #port: 8089
  #contextPath: /paypalservice

spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: create-drop
    hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  datasource:
    url: jdbc:mysql://localhost:3306/list?useSSL=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jackson.serialization.write-dates-as-timestamps: false

fraudValidator:
  enabled: false
  maxAccountWindow: 10
  maxAccountForWindow: 4
  maxAccountsForToday: 3
  maxPaymentWindow: 3
  maxPaymentForWindow: 20
  maxPaymentForToday: 10
  maxPaymentOkWindow: 3
  maxPaymentOkForWindow: 10
  maxPaymentOkForToday: 5
  maxSumTotalAmountWindow: 3
  maxSumTotalAmountForWindow: 1000
  maxSumTotalAmountForToday: 500
  maxPaypalWindow: 3
  maxPaypalForWindow: 5
  maxPaypalForToday: 3
  fraudPaypalWhiteList: psg_fraud_paypal_whiteList
